### ISSUE TITLE
1.0.0.5 doesnt work

### ISSUE THREAD

**Issue by vveed** [TonCunha/multi-microsoft-teams#16]
Hello, 
1.0.0.5 doesnt work 
1.0.0.4 works

whats the matter why it doesnt work? 

I have installt on W1064:
windowsdesktop-runtime-3.1.10-win-x64

If i make a profile and click "launch" nothing happend.

**Comment by Ztarbox** [comment]
Thats because one codeline from my PR wasn't merged:
https://github.com/TonCunha/multi-microsoft-teams/pull/14/commits/760db8e535c732e76f8311d3288dc982c4c2ac18#diff-c8c3685f01864b06f65dc0b0b9dcc387c3647b2b2ebb80f5acb69d872ec04b83L9

The Property `Profile.IsEnabled` is used in a Binding in yaml.

Cause of this, I have my own version up and running.
Which als allows Multi-Select, caus I like it.

https://github.com/Ztarbox/multi-microsoft-teams/releases

**Comment by TonCunha** [comment]
In the new version this error will be resolved.
